### ISSUE TITLE
GC Factory GUI

### ISSUE THREAD

**Issue by jcmbennett** [Ls-Modcompany/FS19_GlobalCompany#63]
I am not sure if this is normal as it is the development version but wanted to make sure I was not missing something. When in the CG Menu under all my factories for the input and output it shows $|10n_GC_gui as shown in the SS.

![image](https://user-images.githubusercontent.com/25438829/69499388-78aa2d00-0ea6-11ea-966b-b3d4b791507f.png)

**Comment by Roby1164** [comment]
But you don't have the latest version, that's a mistake that was fixed long ago.

**Comment by jcmbennett** [comment]
I am running 1.1.3.0, If there is a newer version please direct me to the link.

**Comment by jcmbennett** [comment]
Ok, I think I have figured it out. I need to download the master files, zip and update to server.

**Comment by jcmbennett** [comment]
I updated to the version 1.1.3.1 yet still have the same results. Are there other mods required?

**Comment by jcmbennett** [comment]
![cg2](https://user-images.githubusercontent.com/25438829/69500847-b82b4600-0eb3-11ea-901d-c7d86210bb5e.jpg)
![cg1](https://user-images.githubusercontent.com/25438829/69500845-b5c8ec00-0eb3-11ea-9494-d9fb5fd58dfc.jpg)

**Comment by Roby1164** [comment]
But do they have that mistake only those Mods or even others?
It almost seems that the mod doesn't have the GC_Checker.lua file inside.

**Comment by Roby1164** [comment]
Are they mod or integrated into the map?

**Comment by jcmbennett** [comment]
They are all mods for the map, not integrated. Every single factory is the same. I usually get an error if a GC_Checker.lua file is missing but I will check that.

**Comment by jcmbennett** [comment]
Ok so the factory mods have the GC_Checker.lua file but not the FS19_GlobalCompany mod itself. I downloaded all the files just today so if it is required then it must not be in the master directory here.

**Comment by Roby1164** [comment]
The Mod GC does not need to have that file, that is dedicated to the mods that use the GC.
What map is it? And what are the mods? From the images and names, I can't identify them.

**Comment by jcmbennett** [comment]
PV Industries and all of the factories that dajnet has made as stand alone modes for his PV maps.

**Comment by jcmbennett** [comment]
Sawmill and all the extensions, orchards, greenhouses, warehouses, etc.

**Comment by Roby1164** [comment]
Ok now I see to download it and try it, as soon as I can I update you

**Comment by jcmbennett** [comment]
Thank you very much for your help!

**Comment by Roby1164** [comment]
Downloaded the latest map version and a mod, proven, and everything works.
![Screenshot_3](https://user-images.githubusercontent.com/24955554/69503331-11799080-0f19-11ea-99f5-4dc6cf6c71f9.jpg)

**Comment by jcmbennett** [comment]
I appreciate the help and know I know that it should be working but for some reason it is not working for me on either single player or mp server. I just tried again, deleted my mods folder, downloaded just the map, GC and one factory mod, started new game and same results I have always had. 

So the question is what could cause this? I got PV Industry version 1.9.2 from the new pvmod website as well as the factory mods. The GlobalCompany mod i got from here, the master 1.1.3.1. Those $|10n_gui lines, is that info supposed to come from the GC mod or from each factory mods? I have done all the basic troubleshooting so I need more technical help on where to go now.

**Comment by Roby1164** [comment]
I advise you to check the log file, if not, it contains errors.
The Mods must contain the l110 file, with the description and the various names, then also the Lua GC_Checker file.
Yesterday I tried with a mod at random, and as you saw it worked, I didn't try any others, and I can't say that they all work, but it's still a problem of the Mod, not of the GC.
Even the language with which you play is important, if it is not supported or incomplete, it can create these errors, even if it should say that the name or description is missing in the file l110n.
Let's see if @kevink98, maybe read and can have other indications.

**Comment by jcmbennett** [comment]
Ok, so I just tried a new game with only the Industry map, Global Company and Chipboard factory mod as you tested, no other mods and still same incorrect results. I checked the chipboard mod and it does have both the GC_Checker.lua and the l10n_en.xml so the only difference that I can see between your test and mine would be the language. 

Also I have tried this on several different computers and game accounts with the same results.
No errors or warning in the log file or in the GC log.

l10n_en.xml File Contents:

"<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<l10n>
	<elements>
		<e k="GlobalCompanyPlaceable_chipboardFactory_FactoryName" v="Chipboard Factory"/>
		<e k="GlobalCompanyPlaceable_chipboardFactory_FactoryDescription" v="Creates chipboard from woodchips and glue"/>
		<e k="GlobalCompanyPlaceable_chipboardFactory_Input1" v="Woodchips"/>
		<e k="GlobalCompanyPlaceable_chipboardFactory_Input2" v="Glue"/>
		<e k="GlobalCompanyPlaceable_chipboardFactory_productLine_1" v="Chipboard Production"/>
						
	</elements>
</l10n>"

GC_Checker.lua:

-- GC_Checker
--
-- @Interface: 1.4.0.0 b5007
-- @Author: LS-Modcompany / GtX
-- @Date: 24.04.2019
-- @Version: 1.1.0.0

**Comment by kevink98** [comment]
With which language do you play?

**Comment by jcmbennett** [comment]
english

**Comment by kevink98** [comment]
Try the acutal version: https://github.com/Ls-Modcompany/FS19_GlobalCompany (is not a new version).

**Comment by jcmbennett** [comment]
I have tried versions 1.1.1.0, 1.1.2.0, 1.1.3.0 and 1.1.3.1 all with same results. Is there another version I am not finding?

**Comment by jcmbennett** [comment]
OK I removed everything game, mods folders and all. Downloaded the map a factory and GC 1.1.3.1 and new game. Finally it worked for the first time! Now i just need to make that work on my mp server. :) Thank you so very much for all your help. It was driving me crazy.

**Comment by Pyrjo** [comment]
I have this problem also, i started FS19_Hopfach with version 1.1.0.0. works perfect. but when i start it in 1.1.3.0 i get this error when open the old save file. if i start a new from scratch i get this error. 
![image](https://user-images.githubusercontent.com/59116717/71308708-11798d00-2400-11ea-9d8d-a23911eb3c24.png)

**Comment by Pyrjo** [comment]
https://www.youtube.com/watch?v=EeWvPW5nPA4
Clearly it should work with this mod and the map. So what makes it crash?

![image](https://user-images.githubusercontent.com/59116717/71308756-8f3d9880-2400-11ea-99d6-12d25e21bb05.png)
